name: CI

on:
  push:
    branches: [ main, feature/config-logging ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore SimpleApiServer/SimpleApiServer.sln

      - name: Build
        run: msbuild SimpleApiServer/SimpleApiServer.sln /p:Configuration=Release
